version: "3"

services:
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
    command: redis-server
    restart: always

  nest:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: dockerfile
    image: nest-prod
    container_name: nest-prod
    ports:
      - 3000:3000
    # volumes:
    #   - ./app/logs:/usr/server/logs

    env_file: ./mohae/.env.production
    restart: always
# 도커 컴포즈로 띄는 이미지들은 하나의 네트워크를 공유하므로 별도의 설정을 해줄 필요가 없기 때문에 네트쿼크 대역을 명시하지 않았음

